### ISSUE TITLE
除濕機F-Y32EH完全無法載入使用

### ISSUE THREAD

**Issue by andysquall** [osk2/panasonic_smart_app#100]
除濕機F-Y32EH完全無法載入使用
我可以分享我的除濕機給你操作
![F-Y32EH](https://github.com/osk2/panasonic_smart_app/assets/157889351/b26859fc-6756-4f17-929c-1810fd499725)
![image](https://github.com/osk2/panasonic_smart_app/assets/157889351/3761f742-65c8-4c55-9b45-fa2444349f22)

**Comment by osk2** [comment]
看看日誌裡面是不是有超量使用的錯誤，是的話先停用套件半天再重新啟用試試
