### ISSUE TITLE
除濕機無法顯示實體

### ISSUE THREAD

**Issue by yiminglee790514** [osk2/panasonic_smart_app#102]
![123](https://github.com/osk2/panasonic_smart_app/assets/142093114/55513544-94c7-4199-86d1-e4eebfe9d3ab)
![456](https://github.com/osk2/panasonic_smart_app/assets/142093114/9a851042-daa4-4df9-b6c2-ebb7b4132dd3)
![789](https://github.com/osk2/panasonic_smart_app/assets/142093114/79246144-e25a-4f3b-9a20-d97b7e5dc783)
![000](https://github.com/osk2/panasonic_smart_app/assets/142093114/c31739c6-b577-441d-978c-79001d4445c2)

**Comment by earthqmei** [comment]
我也有這個問題，而且耗能、濕度不會更新。嘗試過刪掉integration再重新登入，可以更新一次濕度，但後來還是不能控制，也不再更新。

原廠的App是可以用的

**Comment by yiminglee790514** [comment]
v2.8.0也不行
![111](https://github.com/osk2/panasonic_smart_app/assets/142093114/b28c4a7a-1b33-4bbd-8719-a6349e1dcbf8)
![222](https://github.com/osk2/panasonic_smart_app/assets/142093114/df41102f-d298-4833-8c0f-50aff566dab6)

**Comment by eric2q** [comment]
我觀察到是HA core 2024.2.X的問題，退回2024.1.6，就恢復正常了

**Comment by earthqmei** [comment]
哈哈 我也是喔，原本在2024.1都沒有問題，是升到2024.2才出現問題

**Comment by yiminglee790514** [comment]
更新後已解決
![777](https://github.com/osk2/panasonic_smart_app/assets/142093114/7337a5b6-1e17-497d-b48a-5a11ea30aeff)
![888](https://github.com/osk2/panasonic_smart_app/assets/142093114/0986be10-d73b-489e-918b-5f6f5e6c1006)

**Comment by earthqmei** [comment]
我更新後還是不行呢
![IMG_5265](https://github.com/osk2/panasonic_smart_app/assets/55537221/c345e6ea-22b6-4d88-96ef-fd0183231d2c)
![image](https://github.com/osk2/panasonic_smart_app/assets/55537221/241f1941-ffde-4fbb-8b1e-77a26d01999f)

Logger: homeassistant.setup
Source: setup.py:404
First occurred: 10:53:24 (2 occurrences)
Last logged: 22:33:21

Unable to prepare setup for platform 'panasonic_smart_app.humidifier': Platform not found (cannot import name 'HumidiferDeviceClass' from 'homeassistant.components.humidifier' (/usr/src/homeassistant/homeassistant/components/humidifier/__init__.py)).

**Comment by osk2** [comment]
可以試試清掉套件快取

```bash
rm -r /config/custom_components/panasonic_smart_app/__pycache__
```

之後重開 HA

**Comment by earthqmei** [comment]
嘗試兩次用ssh去刪除快取、重啟、刪掉裝置重新登入都不行。後來我從HACS整個刪掉，確認cache也都不存在了，再重頭安裝就沒問題了。感謝協助！

**Comment by umas2019** [comment]
我這邊也有一樣的問題，從HACS整個刪掉也不行，我看的到一台除濕機，另一台就沒辦法。但從官方的APP是OK的

**Comment by osk2** [comment]
> 我這邊也有一樣的問題，從HACS整個刪掉也不行，我看的到一台除濕機，另一台就沒辦法。但從官方的APP是OK的

單一台除濕機消失就不是這個 issue 的問題了，看看日誌裡面有什麼錯誤？

**Comment by umas2019** [comment]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:352
Integration: 感測器 (documentation, issues)
First occurred: 上午12:53:02 (1 occurrences)
Last logged: 上午12:53:02

Error while setting up panasonic_smart_app platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 352, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 533, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 782, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1325, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 989, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1110, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1049, in __async_calculate_state
    attr.update(self.state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 453, in state_attributes
    raise ValueError(
ValueError: Entity sensor.fang_jian_chu_shi_ji_ben_yue_hao_dian_liang (<class 'custom_components.panasonic_smart_app.sensor.PanasonicEnergySensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured.

**Comment by osk2** [comment]
這個問題在 v2.8.1 修正了，不幸的是又出現新的問題被我暫時撤回了

目前可以先照著[這裡的說明](https://github.com/osk2/panasonic_smart_app/issues/101#issuecomment-1946766358)自行修正

**Comment by umas2019** [comment]
> 這個問題在 v2.8.1 修正了，不幸的是又出現新的問題被我暫時撤回了
> 
> 目前可以先照著[這裡的說明](https://github.com/osk2/panasonic_smart_app/issues/101#issuecomment-1946766358)自行修正

按照那篇的方法已成功解決解決問題，至少目前可以做，原來可以在另一篇找到解決，感謝您的辛苦

**Comment by osk2** [comment]
除濕機實體消失的各位可以試試 [v2.8.2](https://github.com/osk2/panasonic_smart_app/releases/tag/v2.8.2)
