### ISSUE TITLE
冷氣中的本月耗電量變成不可用

### ISSUE THREAD

**Issue by yourcst** [osk2/panasonic_smart_app#104]
冷氣中的本月耗電量在升級到本月新版後就無法再次使用.
目前版本 v2.8.0
Core  : 2024.3.1
Supervisor : 2024.03.0
Operating System : 12.1

**Comment by osk2** [comment]
嗨，可以先照著[這邊的步驟](https://github.com/osk2/panasonic_smart_app/issues/101#issuecomment-1946766358)自行處理

**Comment by yourcst** [comment]
謝謝回答.本月耗電量重新出現了..
