### ISSUE TITLE
台灣Ux系列無法使用

### ISSUE THREAD

**Issue by yue830219** [osk2/panasonic_smart_app#109]
我們家三台UX冷氣能接入 但無法使用

**Comment by osk2** [comment]
冷氣實體顯示為不可用嗎？是的話麻煩附上 debug log，日後可以加入支援

**Comment by sahsu** [comment]
最新的 patch 所有東西合 pm2.5/電力預測消耗等sensor都正常了喔!!

<img width="1060" alt="image" src="https://github.com/user-attachments/assets/6b6e0d0b-420b-4c2a-b4b5-743007d5cdfe">
