### ISSUE TITLE
F-Y20JH V2.81異常

### ISSUE THREAD

**Issue by andy860218** [osk2/panasonic_smart_app#113]
F-Y20JH除濕機以下問題請再協助 謝謝
1.無法像冷氣使用溫控器面板
2.找不到開關機選項
3.pm2.5 異味 sensor無法接收
![B](https://github.com/user-attachments/assets/f238ef5b-c08f-4265-8746-5abc8411feb8)

**Comment by osk2** [comment]
[v2.8.2](https://github.com/osk2/panasonic_smart_app/releases/tag/v2.8.2) 修正了一些除濕機的問題，試試看還有沒有問題

**Comment by andy860218** [comment]
您好，溫控器面板已正常
目前問題
1.pm2.5 、異味 sensor無法接收
2.常常發生statue執行失敗，需重置HA才可以(如圖，左下角訊息)
![NG](https://github.com/user-attachments/assets/1f467ed3-d598-4622-b240-9a9a6c43c998)
