### ISSUE TITLE
Panasonic 的App 改名成為 IoT ，是不是不能用了？

### ISSUE THREAD

**Issue by chenca227888** [osk2/panasonic_smart_app#120]
從HACS下載了這個app後，在settings > device 只有看到 "update"狀態，沒有任何裝置顯示，是已經不支援了嗎？(第一次使用 panasonic 相關 app)

**Comment by osk2** [comment]
從 HACS 下載後還需要到 settings -> integrations 右下角找 ADD INTEGRATION，接著按照一般步驟完成設定就行了

**Comment by chenca227888** [comment]
原來如此！謝謝！
