### ISSUE TITLE
如何取得 send_command() 所需的 command ID？

### ISSUE THREAD

**Issue by lcy0321** [osk2/panasonic_smart_app#124]
Hi Experts,

我正在試著加入冰箱的邏輯
https://github.com/lcy0321/panasonic_smart_app/commit/290ca7b9251358cb1b9b4ded56dc5a3378c038a9

目前已經能在 HA 上面看到像是溫度和除霜狀態的數值
像快速製冰和停止製冰的部分，可能還需要從 binary_sensor 改成 switch，才能控制這些狀態

目前的疑問是
像讀取狀態所需的 command ID，可以從 `get_devices()`（UserGetRegisteredGwList2 API）取得
那設定狀態用的 command ID 是怎麼取得的呢？
例如像這裡的 `155`
https://github.com/osk2/panasonic_smart_app/blob/9b4e0e92002a1f91c35b47ee159102cee17f5d98/custom_components/panasonic_smart_app/switch.py#L245

是有哪個 API 拿的到這些資訊嗎？還是說是透過 MITM 去拿的？
如果是 MITM，也想了解一下你們大概是用什麼工具去做的。

謝謝

**Comment by osk2** [comment]
Hello,
我之前的解法供你參考
https://github.com/osk2/panasonic_smart_app/issues/74#issuecomment-1633416503

**Comment by osk2** [comment]
酷！這個發現對後面的開發幫助蠻大的
最近有空也打算支援一下智慧開關，再來試試這招 👍
