### ISSUE TITLE
希望能加入洗衣機系列

### ISSUE THREAD

**Issue by Aaron3188** [osk2/panasonic_smart_app#15]
希望能加入洗衣機NA系列
例如`NA-V160HDH`
能通知衣物洗完或行程設定
謝謝

PS. 原廠台製APP一言難盡

**Comment by osk2** [comment]
這有在計劃之中，但會等冷氣和除濕機功能較完善之後才會開始進行

**Comment by leoyangt** [comment]
Hi Osk2
Thanks for great work on Panasonic.
Plz add support on washing machine NA-V180HDH
Thanks a lot

**Comment by 1043717432** [comment]
謝謝，可以支持中國大陸的賬號登陸嗎？我使用的是大陸的賬號和APP，無法登陸，我只想要知道我的冰箱狀態和洗衣機狀態做場景提醒！

**Comment by 1043717432** [comment]
我來試試看用大陸區賬號登陸台灣APP看能否使用。謝謝！

**Comment by Aaron3188** [comment]
Hi Osk2,
Thank you, so there is support `NA-V160HDH` in **v2.3**?

**Comment by osk2** [comment]
The support of washing machine will be included in next milestone (which is 2.3). There is no ETA yet since I don't have time to work on this.

**Comment by osk2** [comment]
這幾天先實作了幾個洗衣機的狀態

1. 洗衣時間偵測器
2. 運轉狀態偵測器
3. 洗衣模式偵測器
4. 洗衣行程偵測器

我自己不太熟洗衣機的操作，不確定這樣是否夠用
有興趣的朋友可以先把 master clone 回去試試看，我再依照反饋來改進

**Comment by 1043717432** [comment]
謝謝，不知道大陸app是否可以，我是大陸用戶，感謝你的分享！！

**Comment by cnbb002** [comment]
我是大陆用户，尝试过大陆app无法登陆，希望可以支援

**Comment by osk2** [comment]
@1043717432 @cnbb002 我剛剛稍微研究了一下，兩地的 app 跟伺服器都是分開的，是兩套獨立的系統，沒辦法在這裡加入支援

**Comment by osk2** [comment]
Released some entities in [v2.4.0](https://github.com/osk2/panasonic_smart_app/releases/tag/v2.4.0). Closed as not receiving feedback.
