### ISSUE TITLE
Failed to access API. Returned 429: "系統檢測您當前超量使用"

### ISSUE THREAD

**Issue by clspeter** [osk2/panasonic_smart_app#16]
昨天開始連線不正常，一直429，IP有換過結果相同。
目前是有六台冷氣在這個帳號，在麻煩查看下，謝謝。
```
This error originated from a custom integration.

Logger: custom_components.panasonic_smart_app.smartApp
Source: custom_components/panasonic_smart_app/smartApp/__init__.py:159
Integration: Panasonic Smart App (documentation, issues)
First occurred: 1:09:50 PM (40 occurrences)
Last logged: 1:09:50 PM

Failed to access API. Returned 429: "系統檢測您當前超量使用"
```

**Comment by osk2** [comment]
看來是這幾天 Panasonic 開始在擋連線了，若被擋掉的話會連官方 App 都無法正常使用，目前封鎖時間未知（可能長達數小時）

我目前在調整架構來減少連線頻率，目前只能先自行停用 HA 套件，至少讓 App 在解除封鎖後能正常使用

**Comment by osk2** [comment]
這一兩天測試的結果看起來是 request 間隔太短就會觸發 429 error

臨供一個臨時的解法：

https://github.com/osk2/panasonic_smart_app/blob/master/custom_components/panasonic_smart_app/smartApp/__init__.py#L120

在120行的地方加入

```python
@Throttle(REQUEST_THROTTLE)
```
這樣能在每個 request 之間延遲五秒，缺點是更新資料的時間會非常的長，但至少是可以運作的

**Comment by clspeter** [comment]
只加一行@Throttle(REQUEST_THROTTLE)我跑不起來
```
This error originated from a custom integration.

Logger: custom_components.panasonic_smart_app
Source: custom_components/panasonic_smart_app/smartApp/__init__.py:80
Integration: Panasonic Smart App (documentation, issues)
First occurred: 11:02:47 AM (1 occurrences)
Last logged: 11:02:47 AM

Unexpected error fetching Panasonic Smart Application data: 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 30, in wrapper_call
    return await func(*args, **kwargs)
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 80, in get_devices
    self._devices = response["GWList"]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 147, in _async_update_data
    return await self.update_method()
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 36, in wrapper_call
    return await func(*args, **kwargs)
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 80, in get_devices
    self._devices = response["GWList"]
TypeError: 'NoneType' object is not subscriptable

```
如果是用fix/reduce-request-freq 下去跑
一開始載入的資訊都正常，實際操作也有作用，但在HA上狀態不會更新

**Comment by osk2** [comment]
昨天也有發現 `TypeError: 'NoneType' object is not subscriptable` 的問題，我還在找原因 🤦🏼 

`fix/reduce-request-freq` 這 branch 還沒完成，現況就如你說的這樣，一開始寫得很開心，後來測完才知道寫法錯了XD

**Comment by osk2** [comment]
@clspeter 剛在 `fix/reduce-request-freq` 推了一版，再麻煩協助測試一下

**Comment by clspeter** [comment]
哈哈，了解
目前測起來是正常運作
但entity的名稱沒有載入，entity id則是16進位的數值且都相同，手動改成原本的就可以了
Device ID則有正確

**Comment by osk2** [comment]
Fixed in badc4d4a4561fa6ae5cec74516e94d382df86049.

**Comment by osk2** [comment]
Entity 名稱剛沒注意到，我放在另一個 commit

這問題在 [v1.3.0](https://github.com/osk2/panasonic_smart_app/releases/tag/v1.3.0) 裡都處理掉了

**Comment by clspeter** [comment]
感謝更新
但昨晚運作一陣子又跳429了
先刪掉一個晚上再加入。目前正常中，再觀察看看
```
This error originated from a custom integration.

Logger: custom_components.panasonic_smart_app.smartApp
Source: custom_components/panasonic_smart_app/smartApp/__init__.py:200
Integration: Panasonic Smart App (documentation, issues)
First occurred: July 13, 2021, 9:02:04 PM (1628 occurrences)
Last logged: 1:57:54 AM

Failed to access API. Returned 429: "系統檢測您當前超量使用"
```

**Comment by osk2** [comment]
看起來蠻嚴重的，我自己帳號底下四台裝置放了一整天都還沒跳超量使用的錯誤，不知道你帳號底下有多少裝置？

**Comment by clspeter** [comment]
我總共六台冷氣，目前連線是正常了再觀察看看

**Comment by clspeter** [comment]
五點多又遇到了 ，晚點我刪掉兩台再試看看
```
This error originated from a custom integration.

Logger: custom_components.panasonic_smart_app.smartApp
Source: custom_components/panasonic_smart_app/smartApp/__init__.py:200
Integration: Panasonic Smart App (documentation, issues)
First occurred: 5:13:29 PM (1374 occurrences)
Last logged: 10:27:13 PM

Failed to access API. Returned 429: "系統檢測您當前超量使用"
```

**Comment by osk2** [comment]
我在測試時是發現打 API 的間隔在一秒內就會觸發超量使用的錯誤，後來才改成每次間隔都至少要兩秒

但現在看來 API 的 rate limit 規則應該沒這麼簡單，猜測除了間隔過短以外，一定時間內打太多次也會觸發錯誤，若你減少裝置數就恢復正常的話就能證實這個猜測了

**Comment by DidibabaQiu** [comment]
> 我在測試時是發現打 API 的間隔在一秒內就會觸發超量使用的錯誤，後來才改成每次間隔都至少要兩秒
> 
> 但現在看來 API 的 rate limit 規則應該沒這麼簡單，猜測除了間隔過短以外，一定時間內打太多次也會觸發錯誤，若你減少裝置數就恢復正常的話就能證實這個猜測了

我只有一台除濕機, 也是一直顯示超量使用, 還好只先買了一台他家的智慧家電... 
v1.3一出來我就刪除原本的重新安裝, 不行; 昨天刪除原本的整合, 今天再加, 也是不行, 歐大辛苦了, 簡直小蝦米對抗大鯨魚XD

Logger: homeassistant.components.humidifier
Source: /usr/local/lib/python3.9/asyncio/events.py:80
Integration: 加濕器 (documentation, issues)
First occurred: 2021年7月14日 13:29:47 (2 occurrences)
Last logged: 09:44:34

Setup of humidifier platform panasonic_smart_app is taking over 10 seconds.

**Comment by osk2** [comment]
> Logger: homeassistant.components.humidifier
> Source: /usr/local/lib/python3.9/asyncio/events.py:80
> Integration: 加濕器 (documentation, issues)
> First occurred: 2021年7月14日 13:29:47 (2 occurrences)
> Last logged: 09:44:34
> 
> Setup of humidifier platform panasonic_smart_app is taking over 10 seconds.

@DidibabaQiu 這段 log 只能看出整合載入時間比較久而已，沒有錯誤

**Comment by DidibabaQiu** [comment]
> > Logger: homeassistant.components.humidifier
> > Source: /usr/local/lib/python3.9/asyncio/events.py:80
> > Integration: 加濕器 (documentation, issues)
> > First occurred: 2021年7月14日 13:29:47 (2 occurrences)
> > Last logged: 09:44:34
> > Setup of humidifier platform panasonic_smart_app is taking over 10 seconds.
> 
> @DidibabaQiu 這段 log 只能看出整合載入時間比較久而已，沒有錯誤

不好意思，打字寫超量，貼文貼到超時XD

我昨天又刪掉一次, 今天看到您又有更新版本馬上安裝看看, 結果還是超量!
然後我發現: 我在家使用手機APP死活登不上, 無論wifi或4G都不行, 一來公司就OK(插件還是不行), 哈哈該不會連我IP都封鎖了XD
----------------------
自訂整合產生錯誤。

Logger: custom_components.panasonic_smart_app.smartApp
Source: custom_components/panasonic_smart_app/smartApp/__init__.py:200
Integration: Panasonic Smart App (documentation, issues)
First occurred: 08:58:35 (61 occurrences)
Last logged: 09:59:01

Failed to access API. Returned 429: "系統檢測您當前超量使用"

-----------------------
另外還有幾個錯誤, 歐大您看有沒有幫助? 小弟除濕機無法接入的問題沒有任何急迫性, 請歐大不要太辛苦, 有空的話再看, 發現您的插件每次都是半夜在更新^^"
-----------------------
自訂整合產生錯誤。

Logger: homeassistant
Source: custom_components/panasonic_smart_app/sensor.py:115
Integration: Panasonic Smart App (documentation, issues)
First occurred: 08:58:35 (60 occurrences)
Last logged: 09:59:01

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 453, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 425, in _stringify_state
    state = self.state
  File "/config/custom_components/panasonic_smart_app/sensor.py", line 115, in state
    status = self.coordinator.data[self.index]["status"]
KeyError: 0
------------------------------
自訂整合產生錯誤。

Logger: homeassistant
Source: custom_components/panasonic_smart_app/binary_sensor.py:46
Integration: Panasonic Smart App (documentation, issues)
First occurred: 09:58:01 (1 occurrences)
Last logged: 09:58:01

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 419, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 453, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 423, in _stringify_state
    if not self.available:
  File "/config/custom_components/panasonic_smart_app/binary_sensor.py", line 46, in available
    status = self.coordinator.data[self.index]["status"]
KeyError: 0
-----------------------------
自訂整合產生錯誤。

Logger: custom_components.panasonic_smart_app
Source: helpers/update_coordinator.py:219
Integration: Panasonic Smart App (documentation, issues)
First occurred: 09:58:01 (1 occurrences)
Last logged: 09:58:01

Error fetching Panasonic Smart Application data: Failed on initialize
------------------------------
自訂整合產生錯誤。

Logger: custom_components.panasonic_smart_app.smartApp
Source: custom_components/panasonic_smart_app/smartApp/__init__.py:186
Integration: Panasonic Smart App (documentation, issues)
First occurred: 09:57:53 (1 occurrences)
Last logged: 09:57:53

Failed to access API. Returned 417: 此CPToken已經逾時

----------------------------------

**Comment by clspeter** [comment]
四台冷氣，昨天三點多還是爆了，這次應該有十幾個小時
六台兩三個小時就爆了
等恢復之後我在試看看三台會不會爆
還想請教一下若有自動化的話會影響到API存取的次數嗎?

**Comment by osk2** [comment]
Automation 不會影響到才是，他不會主動去更新數據，而是監聽實體的數據

目前的設計是每分鐘更新一次狀態，改版前一個 entity 就會查詢一次狀態，更新一輪下來數量就相當可觀
新版改成一部裝置只會查詢一次，每部裝置查詢間隔一秒，但其實更新數據拖太久的話，這輪還沒結束，下一輪又開始了，可能就是這樣導致觸發超量錯誤

或許可以試試把 [`UPDATE_INTERVAL`](https://github.com/osk2/panasonic_smart_app/blob/master/custom_components/panasonic_smart_app/const.py#L29) 改為 120 看會不會有改善

BTW 我四部裝置也是24小時內就收到超量錯誤了

**Comment by Wonsle** [comment]
我也來回報一下，裝置只有一台冷氣就收到超量
Logger: custom_components.panasonic_smart_app.smartApp
Source: custom_components/panasonic_smart_app/smartApp/__init__.py:200
Integration: Panasonic Smart App (documentation, issues)
First occurred: 11:17:33 (1 occurrences)
Last logged: 11:17:33

Failed to access API. Returned 429: "系統檢測您當前超量使用"

**Comment by clspeter** [comment]
三台冷氣，改120，不到24小時，也是超量了
等解ban我再拉長時間測試看看

**Comment by yen02700** [comment]
前兩天除濕機一直連不上，前天連除濕機的wifi燈都閃起來，直接斷線了
剛才重裝後，登入smart app 的帳號都不行，直接跳錯誤
這是因為被ban的關係嗎? 多久才會解ban啊?

`2021-07-17 15:54:51 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 429: "系統檢測您當前超量使用"
2021-07-17 15:54:51 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 我的帳號 for panasonic_smart_app`

`File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
result = await component.async_setup_entry(hass, self) # type: ignore
File "/config/custom_components/panasonic_smart_app/__init__.py", line 42, in async_setup_entry
await client.login()
File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 68, in login
response = await self.request(
File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 49, in wrapper_call
results = await asyncio.gather(
File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 210, in request
raise PanasonicExceedRateLimit
custom_components.panasonic_smart_app.smartApp.exceptions.PanasonicExceedRateLimit: Reached API rate limit. Please try again later.`

**Comment by yen02700** [comment]
> test
test
`test
test`

#test

**Comment by osk2** [comment]
> 前兩天除濕機一直連不上，前天連除濕機的wifi燈都閃起來，直接斷線了
> 剛才重裝後，登入smart app 的帳號都不行，直接跳錯誤
> 這是因為被ban的關係嗎? 多久才會解ban啊?
> 
> > 2021-07-17 15:54:51 ERROR (MainThread) [custom_components.panasonic_smart_app.smartApp] Failed to access API. Returned 429: "系統檢測您當前超量使用"
> > 2021-07-17 15:54:51 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry 我的帳號 for panasonic_smart_app
> 
> > File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
> > result = await component.async_setup_entry(hass, self) # type: ignore
> > File "/config/custom_components/panasonic_smart_app/**init**.py", line 42, in async_setup_entry
> > await client.login()
> > File "/config/custom_components/panasonic_smart_app/smartApp/**init**.py", line 68, in login
> > response = await self.request(
> > File "/config/custom_components/panasonic_smart_app/smartApp/**init**.py", line 49, in wrapper_call
> > results = await asyncio.gather(
> > File "/config/custom_components/panasonic_smart_app/smartApp/**init**.py", line 210, in request
> > raise PanasonicExceedRateLimit
> > custom_components.panasonic_smart_app.smartApp.exceptions.PanasonicExceedRateLimit: Reached API rate limit. Please try again later.

照我的經驗只要幾分鐘內不要動作（套件和app都不要使用）應該就會解除封鎖

除濕機無法連線的問題我也有遇到，目前人不在家還不知道是什麼問題，或許可以重設智慧模組試試？

**Comment by zaberxxx** [comment]
Error setting up entry zaberxxx@gmail.com for panasonic_smart_app
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/panasonic_smart_app/__init__.py", line 42, in async_setup_entry
    await client.login()
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 68, in login
    response = await self.request(
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 49, in wrapper_call
    results = await asyncio.gather(
  File "/config/custom_components/panasonic_smart_app/smartApp/__init__.py", line 210, in request
    raise PanasonicExceedRateLimit
custom_components.panasonic_smart_app.smartApp.exceptions.PanasonicExceedRateLimit: Reached API rate limit. Please try again later.

Same here, 已經超過24小時沒有使用add-on, 也已經刪掉經由HACS重裝過。
官方App可以登入。

**Comment by clspeter** [comment]
我也完全連不上了，同樣的錯誤訊息，可能是Panasonic又改了

**Comment by andyching168** [comment]
我前幾天四台冷氣改240
到現在還沒出問題過

**Comment by yen02700** [comment]
> 我上週六四台冷氣改240
> 到現在還沒出問題過

我只有一台除濕機，昨天看到跟著設240，設完除濕機還是連不上
不過因為log裡沒看到再發 `429 超量使用`，想說應該OK，就放著等
結果今天發現除濕機wifi 斷線了，查log還是沒看到超量使用被擋的訊息，想說應該和套件沒關係
就重設wifi連線，設定時一直時好時壞，有時機器明明已經設好連上wifi，沒幾分鐘wifi燈又開始閃
一度以為是機器的通訊模組壞了，想說明天要報修了
剛才把套件關了試試，開了半小時都沒斷線
繞了一圈，還是被擋了....Panasonic 擋的真苛..

**Comment by kolicheng** [comment]
回報，跟著設定240，接入Homekit目前查詢數值都是正常的

**Comment by osk2** [comment]
我有嘗試和官方聯繫，還沒得到回覆（也不知道會不會回覆...），在那之前不會有更動

目前只能加大 `UPDATE_INTERVAL`，看來 240 是比較穩定的數值，有遇到超量使用錯誤的話可以再試試調整這組數值
要注意的是把更新間隔拉這麼長會讓整合不能即時反應目前裝置狀態，實際體驗應該蠻差的，只能算是一時的權宜之計

**Comment by drkshen** [comment]
不要說這個 integrations 不穩定, 連 Panasonic smart app 自己常常不正常 40% of time is bad...

**Comment by osk2** [comment]
剛釋出 [v1.3.3](https://github.com/osk2/panasonic_smart_app/releases/tag/v1.3.3) 了

原先帳號內若有離線裝置會導致 HA 一直重試更新數據，可能因為這樣觸發超量使用的錯誤，這版修復了這個問題，同時也調整了下面數值
1. 每個 request 間隔至少兩秒
2. 更新週期（UPDATE_INTERVAL）延長至每 90 秒更新一次
3. 逾時時間延長至 20 秒

我自己四部裝置跑了 12 小時還沒有發現問題，這版打算搜集多一點回饋之後才會正式釋出，目前是以 pre-release 的方式釋出，HACS 一開始沒勾安裝 beta 版的話需要手動下載回去更新

**Comment by andyching168** [comment]
在昨天早上11點設定的
結果晚上七點就報錯了

自訂整合產生錯誤。

Logger: custom_components.panasonic_smart_app.smartApp
Source: custom_components/panasonic_smart_app/smartApp/__init__.py:200
Integration: Panasonic Smart App (documentation, issues)
First occurred: 2021年8月7日 19:52:19 (808 occurrences)
Last logged: 19:55:40

Failed to access API. Returned 429: "系統檢測您當前超量使用"

**Comment by kolicheng** [comment]
回報，一樣升級到1.3.3開了10幾個小時後出現429，我先把UPDATE_INTERVAL從90延長到180再觀察看看

**Comment by osk2** [comment]
昨天發現官方釋出 2.0.0 版的 app，看來有新的 API 能用

我已經實作一版了，先測試個一天沒問題再更新上來

**Comment by DidibabaQiu** [comment]
歐大辛苦了，剛剛更新2.0beta，我的除濕機實體竟然就復活了XD
已經一個月都超量了說， UPDATE_INTERVAL 改為 300也一直都無效，想說就放著，沒想到剛剛竟然恢復正常，歐大一直努力不放棄的精神真是讓人敬佩^^

**Comment by zaberxxx** [comment]
經過這次2.0.0更新，濕度可以運作了，但其他的實體都還是顯示不可用的狀態，去看LOG也沒有超量的問題，請問有什麼可能呢？我已經把整合砍掉重新安裝過了。
<img width="343" alt="截圖 2021-08-10 下午8 11 41" src="https://user-images.githubusercontent.com/73158577/128864930-3fc52b27-5db5-46be-9de4-64afef2733fd.png">

**Comment by zaberxxx** [comment]
> > 經過這次2.0.0更新，濕度可以運作了，但其他的實體都還是顯示不可用的狀態，去看LOG也沒有超量的問題，請問有什麼可能呢？我已經把整合砍掉重新安裝過了。
> 
> 我自己測試起來除濕機的確有些時候會沒有回應，推測是除濕機狀態回應太慢，目前的設計是逾時就視為裝置離線
> 
> 可以先把 [REQUEST_TIMEOUT](https://github.com/osk2/panasonic_smart_app/blob/master/custom_components/panasonic_smart_app/smartApp/const.py#L6) 調整為 30 或更高的數值試試，這我明天有空會再處理
回測報告：
REQUEST_TIMEOUT 試過調了30, 60, 120, 240都一樣，但調到240不會出現“Setup of sensor platform panasonic_smart_app is taking over 10 seconds.“
也試了調整SECONDS_BETWEEN_REQUEST 到 10 但目前看起來一樣，只有濕度有出現。

**Comment by zaberxxx** [comment]
> > 經過這次2.0.0更新，濕度可以運作了，但其他的實體都還是顯示不可用的狀態，去看LOG也沒有超量的問題，請問有什麼可能呢？我已經把整合砍掉重新安裝過了。
> 
> 我自己測試起來除濕機的確有些時候會沒有回應，推測是除濕機狀態回應太慢，目前的設計是逾時就視為裝置離線
> 
> 可以先把 [REQUEST_TIMEOUT](https://github.com/osk2/panasonic_smart_app/blob/master/custom_components/panasonic_smart_app/smartApp/const.py#L6) 調整為 30 或更高的數值試試，這我明天有空會再處理

回測報告：
REQUEST_TIMEOUT 試過調了30, 60, 120, 240都一樣，但調到240不會出現“Setup of sensor platform panasonic_smart_app is taking over 10 seconds.“
也試了調整SECONDS_BETWEEN_REQUEST 到 10 但目前看起來一樣，只有濕度有出現。

**Comment by DidibabaQiu** [comment]
> 10 但目前看起來一樣，只有濕度有出現

回報我自己的情況: 
只要除濕機關機除了濕度以外的實體就會unavailable，開機後就正常(但從HA就也開不了機了，要進原廠APP開)

**Comment by zaberxxx** [comment]
> > 10 但目前看起來一樣，只有濕度有出現
> 
> 回報我自己的情況:
> 只要除濕機關機除了濕度以外的實體就會unavailable，開機後就正常(但從HA就也開不了機了，要進原廠APP開)

試了一下，的確我的除濕機也是這樣。

**Comment by drkshen** [comment]
昨天裝了2.0版, 早上又掉線了. 裝回1.33還是比較穩. 不過2.0版多了幾個控制鈕還不錯

**Comment by osk2** [comment]
除濕機關機後無法控制 (#24)不是 API 的問題，這我會再調整寫法

**Comment by drkshen** [comment]
我是使用冷氣機的部份, 似忽 1.33 的版本比較不會超量使用,  請問 1.33 版的 UPDATE_INTERVAL 是多少?

**Comment by drkshen** [comment]
如果 v1.3.3 是穩定的 (UPDATE_INTERVAL 是 90), v2.0 request 1~3 次 理論上 UPDATE_INTERVAL 要 270. 看起來是短時間 request 太多次的問題

**Comment by drkshen** [comment]
大大, 我昨天有更新了 v2.0.0 版,  但 介面的 "冷氣 操作提示音" 我開了它自動又關, 感覺無法 enable?

**Comment by osk2** [comment]
剛測試的確有這問題，這會在 #27 處理

**Comment by drkshen** [comment]
晚上我想到去用 smart app 打開，然後回 HA 就能用了 :) 但無法 switch XD
