### ISSUE TITLE
function not working after update v2.0.0

### ISSUE THREAD

**Issue by drkshen** [osk2/panasonic_smart_app#33]
大大, 更新後冷氣的室外溫度不顯示, 急冷顯示開的關不掉, 本月耗電量也不顯示, 請查看, 謝謝

**Comment by osk2** [comment]
看起來像是 https://github.com/osk2/panasonic_smart_app/discussions/31

**Comment by drkshen** [comment]
在更 v2.00 前我已經設定在 300sec (6mins) 了

**Comment by osk2** [comment]
v2.1.0 超量使用後，會從另一隻 API 取得數據，可以讓整合保持一直可用的狀態，但僅能得到開關及目前溫/濕度

這時候還是能控制功能通常不受影響，只是控制後狀態不會更新，所以才會有你描述的情況，等到解封之後就會恢復正常了
