### ISSUE TITLE
Loss entity of environmental humidity after upgrade to v2.2.0 from v2.0.0 beta

### ISSUE THREAD

**Issue by zaberxxx** [osk2/panasonic_smart_app#38]
As title
I already tried completely remove the add on and reinstalled. 

![E2004D20-B705-40C1-AFA5-0E15606582AB](https://user-images.githubusercontent.com/73158577/139245250-2179af59-542e-4a4a-8055-b7d037b40443.png)

**Comment by osk2** [comment]
This looks weird. Are you using CZ-T006 for your dehumidifier?

**Comment by zaberxxx** [comment]
Yes, I'm using CZ-T006.

**Comment by zaberxxx** [comment]
I just update my HA core and 6 entities are now available, sorry about reporting this bug.

**Comment by osk2** [comment]
I'll add note in readme in case anyone encounter this issue.
