### ISSUE TITLE
Support PM2.5 for AC

### ISSUE THREAD

**Issue by sugoi-wada** [osk2/panasonic_smart_app#40]
I am trying to add a PM2.5 sensor for ac like this commit. But probably there are some ac's that do not have a PM2.5 sensor. How do you think I should determine this（Model or Device etc...）? 

https://github.com/sugoi-wada/panasonic_smart_app/commit/5daa07f78c8b90edbe8c7225e668e7fcdf42e444

My device
Device: CS-RX63GA2, CS-RX22GA2
Model: CZ-T006

**Comment by osk2** [comment]
API doesn't give us enough information about available sensors.

So I just add sensor entities for everyone and disable them if its value is invalid (which normally is negative value like -12345678)

Ref: https://github.com/osk2/panasonic_smart_app/blob/master/custom_components/panasonic_smart_app/sensor.py#L140

**Comment by sugoi-wada** [comment]
Thanks for your response. I understand. Then I'll test again and create PR later.
