### ISSUE TITLE
When I install this app. Can't open my Ha web UI

### ISSUE THREAD

**Issue by JustinCHEN1993** [osk2/panasonic_smart_app#43]
When I install this app. Can't open my Ha web UI.

Since happened from OS 7

**Comment by osk2** [comment]
What do you mean by "can't open web"? Are there any errors or logs?

**Comment by JustinCHEN1993** [comment]
Sorry about that. I can't duplicate this fail now.

Need the issue happened I can't load  "http://homeassistant.local:8123"

HA system with Windows Hyber-v 
OS version: OS 7.1
Home Assistant core: 2021.12.8

Manually to install app.
Copy custom_components/panasonic_smart_app into your custom_components/.

I will keep tracking if still fail what's log I can provide to you for issue debug?

**Comment by osk2** [comment]
It's very unlikely that custom component will break HA. But you can try to [enable debugging log](https://github.com/osk2/panasonic_smart_app#enable-logs) and post logs here if problem persists.

**Comment by osk2** [comment]
I'm closing this as not receiving any update for ~2 weeks. Feel free to reopen if the problem persists.
