### ISSUE TITLE
冷氣控制器(CZ-T007)韌體更新後，PM2.5感測器未開機回傳65535

### ISSUE THREAD

**Issue by gaozhitw** [osk2/panasonic_smart_app#45]
昨天更新CZ-T007的新韌體後，PM2.5的偵測功能在未開機的情況下，
好像變成回傳65535

![參考](https://i.imgur.com/VLwifMF.png)

**Comment by osk2** [comment]
看起來是這次韌體更新數據格式又變了，原本未開機的狀態會回傳一個負數，現在又改成 65535 🤦🏼
