### ISSUE TITLE
CS-LJ50BA2 操作異常

### ISSUE THREAD

**Issue by skylinegt0310** [osk2/panasonic_smart_app#46]
無法即時更新冷氣狀態
按下功能都能正常操作
但面板數據啟動狀態都無反應

**Comment by osk2** [comment]
裝置狀態不會即時更新，預設每 180 秒更新一次，這是為了避免更新頻率過高被伺服器封鎖（詳情請見 https://github.com/osk2/panasonic_smart_app/discussions/31）

你也可以試著在安裝套件時提高更新頻率，但就無法保證穩定性了

**Comment by osk2** [comment]
沒有收到後續回應，先關掉 issue 了，若有問題請再重新打開
