### ISSUE TITLE
一直無法正常載入(CZ-T007)

### ISSUE THREAD

**Issue by andyching168** [osk2/panasonic_smart_app#47]
Log寫:
Failed to access API. Returned 417: {"State":"fail","StateMsg":"deviceOffline"}
然後是:
Error fetching Panasonic Smart Application data: Failed while updating device status
![image](https://user-images.githubusercontent.com/53651198/160456292-1265bc51-fb62-4817-8bf6-b8994bd0d274.png)
![image](https://user-images.githubusercontent.com/53651198/160456335-216d99d0-eed7-4746-825e-b1dc2318b5ec.png)

**Comment by osk2** [comment]
原廠 API 又改格式了，這會再修正

臨時解法是先不要讓帳號內的裝置離線（斷電或斷網）
