### ISSUE TITLE
Ha無法連線冷氣，但登入panasonic app顯示冷氣連線正常

### ISSUE THREAD

**Issue by percy10442** [osk2/panasonic_smart_app#56]
Ha無法連線冷氣，但登入Panasonic app顯示冷氣連線正常，
不知道是否官方有更換API?

**Comment by osk2** [comment]
HA有顯示什麼錯誤嗎？應該是超量使用了

**Comment by percy10442** [comment]
有顯示超量使用，但以往超量使用Panasonic app的冷氣會無法操控，但這次顯示都正常，所以我才想確認一下是否是官方有更換API。

**Comment by osk2** [comment]
我還沒確認 API 格式有沒有變動

但超量使用不會影響到 HA 控制的部分，詳情可以參考 https://github.com/osk2/panasonic_smart_app/discussions/31

**Comment by percy10442** [comment]
目前已經連接HA都正常了，可能純粹超量使用，我把bug close掉，謝謝。
