### ISSUE TITLE
更新HA日誌出現錯誤

### ISSUE THREAD

**Issue by Naanoda** [osk2/panasonic_smart_app#57]
系統資訊
版本	core-2022.8.1
安裝類別	Home Assistant OS
開發版	false
Supervisor	true
Docker	true
使用者	root
虛擬環境	false
Python 版本	3.10.5
作業系統家族	Linux
作業系統版本	5.15.32-v8
CPU 架構	aarch64
時區	Asia/Taipei
設定目錄	/config
Home Assistant Supervisor
主機作業系統	Home Assistant OS 8.4
更新頻道	stable
Supervisor 版本	supervisor-2022.07.0
Agent 版本	1.2.1
Docker 版本	20.10.14
總磁碟空間	14.2 GB
已使用空間	3.4 GB
健康度	true
支援	true
板	rpi3-64
Supervisor API	ok
版本 API	ok

日誌內容

Logger: homeassistant.components.number
Source: components/number/__init__.py:119
Integration: 數字 (documentation, issues)
First occurred: 05:03:16 (4 occurrences)
Last logged: 05:03:16

custom_components.panasonic_smart_app.number::PanasonicDehumidifierOnTimer is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.panasonic_smart_app.number::PanasonicDehumidifierOffTimer is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.panasonic_smart_app.number::PanasonicACOnTimer is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.
custom_components.panasonic_smart_app.number::PanasonicACOffTimer is overriding deprecated methods on an instance of NumberEntity, this is not valid and will be unsupported from Home Assistant 2022.10. Please report it to the custom integration author.

**Comment by osk2** [comment]
感謝回報，下一版會修復
