### ISSUE TITLE
冷氣多個實體無法使用

### ISSUE THREAD

**Issue by ryanhc0917** [osk2/panasonic_smart_app#60]
你好，我的冷氣是用CZ-T007連接使用，APP版本是2.0.0.33，HA版本2022.10.5
最近在接入HA後控制相關的實體幾乎都無法使用，請問我可以怎麼樣查看問題？
![截圖 2022-10-30 上午12 43 24](https://user-images.githubusercontent.com/114588774/198844339-a2d3a09b-a8dd-4a99-ad78-3648d2789279.png)
![截圖 2022-10-30 上午12 43 03](https://user-images.githubusercontent.com/114588774/198844340-580fdc7c-b2c1-4e05-a75f-cc7381bdffba.png)
![截圖 2022-10-30 上午12 42 43](https://user-images.githubusercontent.com/114588774/198844342-54b86cc5-e4de-4806-bb6e-b67dcdfeac9a.png)

**Comment by osk2** [comment]
裝置未開機的狀態下控制類的實體無法使用是正常的

**Comment by ryanhc0917** [comment]
在我按下HA卡片中按鈕，會執行動作但顯示"climate/set_hvac_mode執行失敗65535"。客廳冷氣一直顯示不可用狀態。

**Comment by osk2** [comment]
有兩件事需要確認：
1. 冷氣顯示為不可用時 app 還能正常使用嗎？
2. 需要知道冷氣和模組的型號，先前有人回報吊隱式冷氣會有異常

**Comment by ryanhc0917** [comment]
感謝你的回覆：
1. 冷氣為不可用時APP仍可正常使用
2. 我有看到吊隱式冷氣因為風向的問題造成異常，對方在程式碼195行加入"try cache"，請問我應該怎麼執行這件事？

**Comment by osk2** [comment]
[最新版](https://github.com/osk2/panasonic_smart_app/archive/refs/heads/master.zip)已經修正這個問題，可以先自行下載回去試試，確定可用後我才會正式發佈更新
