### ISSUE TITLE
濕度回報問題且HA沒有顯示控制面板

### ISSUE THREAD

**Issue by siyb2002** [osk2/panasonic_smart_app#64]
除濕機型號FYV38LX
1. Panasonic app 內 室內濕度未開機87，開機後變67
應該是Panasonic本身的問題
但透過HB把實體（除濕機） 丟給HK 會連帶把濕度也丟過去 造成室內濕度指標異常
2. 除濕機這個實體沒有顯示在裝置內

請問有變通或修正的方式嗎？

**Comment by osk2** [comment]
1. 濕度讀數未開機的情況下偏高是正常的，機器測出來的數值就是這樣，我是不會稱他為異常 😅
2. 先前其他人有反應過，但目前還沒確定問題，也沒什麼時間去修正，可以先嘗試重新設定一下整合

**Comment by siyb2002** [comment]
對..我有問原廠客服 他測出來就是這個數字 ，一點參考價值都沒有 很瞎，順便請問我在HA用HB把除濕機丟到HomeKit 時有沒有技巧把他的濕度bypass 掉 ， 在HK裡看到錯誤的濕度有點困擾從我的iPhone傳送osk2 ***@***.***> 於 2023年3月28日 10:48 寫道：﻿

濕度讀數未開機的情況下偏高是正常的，機器測出來的數值就是這樣，我是不會稱他為異常 😅
先前其他人有反應過，但目前還沒確定問題，也沒什麼時間去修正，可以先嘗試重新設定一下整合

**Comment by osk2** [comment]
我個人猜測可能是未開機時濕氣在機身內不易散去才會造成讀數偏高，開機空氣流動的情況下就會恢復正常

至於你提到的濕度是指除濕機的環境濕度實體嗎？是的話可以修改一下源碼把實體拿掉
手動刪掉下面這一段就可以了
https://github.com/osk2/panasonic_smart_app/blob/master/custom_components/panasonic_smart_app/sensor.py#L68-L75

**Comment by osk2** [comment]
第二點被反應過幾次，我另外開了一個 issue 在 #65，後續進度會在那裡追蹤

沒有其他問題的話這個 issue 就會先關閉

**Comment by siyb2002** [comment]
感謝大大
