### ISSUE TITLE
初始化一直失敗

### ISSUE THREAD

**Issue by e31325** [osk2/panasonic_smart_app#66]
重新下載更新但是一直出現以下錯誤訊息,請問這個要怎麼處理？

自行安裝整合產生錯誤。

Logger: custom_components.panasonic_smart_app
Source: helpers/update_coordinator.py:215 
Integration: Panasonic Smart App (documentation, issues) 
First occurred: 04:11:25 (3 occurrences) 
Last logged: 04:13:18

Error fetching Panasonic Smart Application data: Failed while updating device status

**Comment by osk2** [comment]
有可能是 API 短暫發生問題，可以看一下 log 有沒有記錄到什麼錯誤

參考：[啟用除錯紀錄
](https://github.com/osk2/panasonic_smart_app/blob/master/README-zh.md#%E5%95%9F%E7%94%A8%E9%99%A4%E9%8C%AF%E7%B4%80%E9%8C%84)

**Comment by e31325** [comment]
以寫完指令請問log 要在哪邊看

**Comment by osk2** [comment]
裝置太多或是重試太頻繁都會被封鎖，先將整合停用個半天以上再試一次
