### ISSUE TITLE
Swing Mode 無法設定

### ISSUE THREAD

**Issue by clspeter** [osk2/panasonic_smart_app#7]
用GUI設定Swing Mode成自動以外的角度均會顯示錯誤.
![image](https://user-images.githubusercontent.com/16301430/117563065-f16e6a80-b0d5-11eb-894a-6cf15ce827e2.png)
但如果用遙控器設置好方向之後HA會正確顯示角度.
此狀況下一樣可調回自動但無法調成其他角度
測試冷氣: Panasonic CS-RX71GA2

**Comment by osk2** [comment]
感謝回報，已經修復了，晚點會發布更新

**Comment by osk2** [comment]
@clspeter 我正在整理支援的裝置列表，方便請你回報一下能用的裝置及模組型號有哪些嗎？

**Comment by clspeter** [comment]
已測試室內機型號
CS-RX28GA2
CS-RX36GA2
CS-RX50GA2
CS-RX71GA2
均為內建Wifi

**Comment by osk2** [comment]
Thanks!
