### ISSUE TITLE
冷氣的自動化控制

### ISSUE THREAD

**Issue by ttsmarco** [osk2/panasonic_smart_app#71]
您好，感謝您的付出，製作了這麼好用的HA套件
目前使用上發現一個小問題，故提出一點點小建議

就是明明在冷氣選單中"溫度"、"風速"與"擺動"是能夠控制的
但自動化的選單裡，並無這些選項

由於我是希望能在深夜(入睡後)稍微調高溫度、降低風速並將風向避開吹人
但目前似乎無法做這樣的設定

若可以的話，請加入這樣的設定功能，感謝您

**Comment by osk2** [comment]
我目前沒辦法測試，但這應該是可行的
1. 新增一個 automation 
2. 新增一個 action，並選擇 Call Service
3. service 清單中搜尋 `climate.` 就會列出所有可控制的功能了

上面提到的三個功能都有支援，可以再試試
