### ISSUE TITLE
新增全熱交換器的支援

### ISSUE THREAD

**Issue by OTZro** [osk2/panasonic_smart_app#74]
@osk2 大大，我這邊有 Panasonic 的全熱交換器，想問一下我這邊如果想要加全熱交換器的支援的話，我可以怎麼做呢？如何得知 request 要送哪個代碼呢？

**Comment by osk2** [comment]
分享一下我之前使用的方法：

1. 在電腦上安裝 Android 模擬器
2. 在模擬器安裝 Panasonic app 和 [HTTP Toolkit](https://httptoolkit.com)
3. 在模擬器裡面操作 app 就能攔截所有的 API request

**Comment by osk2** [comment]
v2.10 開始新增全熱交換器的支援，目前測試過的型號如下，有機會可以再試試你的型號能不能正常使用
```
型號：FY-15ZY1W
無線控制器：CZ-T012
```
