### ISSUE TITLE
Cannot log in 

### ISSUE THREAD

**Issue by ARarGithub** [osk2/panasonic_smart_app#75]
Here is the screen shot.

![2023-07-19 14 15 28](https://github.com/osk2/panasonic_smart_app/assets/25960749/a0418ba2-a052-4a94-b003-f2f3db28c8a0)

Got error: User input malformed: expected str for dictionary value @ data['proxy']

**Comment by vixyao** [comment]
I have the same issue today

**Comment by osk2** [comment]
It's been fixed in v2.6.1. The update should be available very soon.
