### ISSUE TITLE
冷氣狀態不會自動更新

### ISSUE THREAD

**Issue by jericho0711** [osk2/panasonic_smart_app#78]
`[家裡3台吊隱式冷氣，在HA內突然都不會自動更新狀態，需要去重新載入app，HA狀態才會當下才會讀取，或是去手機點選HA內的冷氣功能才會更新，確定不是超量api的原因，只是HA內的狀態都不會自動更新，不知道有沒有辦法知道是什麼原因造成的，目前看到有警示訊息只有這個，不知道和這個有沒有關係。

HA的狀態都是2小時前，app的感測溫度已經改變
![image](https://i.imgur.com/0JzUlyR.jpg)
![image](https://i.imgur.com/aeNhPFv.jpg)

Logger: homeassistant.components.sensor
Source: components/sensor/__init__.py:378
Integration: 感測器 ([documentation](https://www.home-assistant.io/integrations/sensor), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+sensor%22))
First occurred: 上午10:38:19 (3 occurrences)
Last logged: 上午10:38:48

Entity sensor.xin_fang_jian_leng_qi_ben_yue_hao_dian_liang (<class 'custom_components.panasonic_smart_app.sensor.PanasonicEnergySensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom integration author.
Entity sensor.zhu_wo_leng_qi_ben_yue_hao_dian_liang (<class 'custom_components.panasonic_smart_app.sensor.PanasonicEnergySensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom integration author.
Entity sensor.yan_fang_jian_leng_qi_ben_yue_hao_dian_liang (<class 'custom_components.panasonic_smart_app.sensor.PanasonicEnergySensor'>) with state_class total_increasing has set last_reset. Setting last_reset for entities with state_class other than 'total' is not supported. Please update your configuration if state_class is manually configured, otherwise report it to the custom integration author.

**Comment by osk2** [comment]
沒有錯誤的話蠻異常的，重開HA能解決嗎？

**Comment by jericho0711** [comment]
昨天將整個APP移除，再重開HA，重裝後目前看來應該是正常了

**Comment by che-chun** [comment]
@jericho0711 請問移除app、重開ha之後，本月耗電量的錯誤，就都不見了嗎？

**Comment by jericho0711** [comment]
@che-chun 我的耗電並沒有錯誤，只是不會自動更新，需要手動載入app，所有的資訊才會更新
不過後來重新安裝就好了，其實已經重新安裝很多次，前天重裝後突然就好了
