### ISSUE TITLE
經常性載入錯誤

### ISSUE THREAD

**Issue by karta028204** [osk2/panasonic_smart_app#79]
![IMG_5866](https://github.com/osk2/panasonic_smart_app/assets/104773377/1b0c1f8f-af42-47f9-a44e-41c3748ab1f2)
![IMG_5867](https://github.com/osk2/panasonic_smart_app/assets/104773377/d28d40fd-deac-40cf-a6da-ac4c3d83c03c)
![IMG_5868](https://github.com/osk2/panasonic_smart_app/assets/104773377/700ba89a-e3a9-4e00-a7cc-2986afae30b8)
 時好時壞重新安裝也無法解決載入問題,但app可以正常使用

**Comment by osk2** [comment]
log 裡面有什麼錯誤嗎？

**Comment by karta028204** [comment]
> log 裡面有什麼錯誤嗎？

要怎麼讀取log

**Comment by osk2** [comment]
目前除了用 proxy 定時換 IP 以外沒有更好的解法了，請參考 https://github.com/osk2/panasonic_smart_app/discussions/31
