### ISSUE TITLE
Panasonic 除濕機 障礙v2.6.1

### ISSUE THREAD

**Issue by eric2q** [osk2/panasonic_smart_app#86]
舊款的 F-Y28CXW 在v2.6.0 運作正常，但是升級到v2.6.1，就無法控制開關，需要降級回到v2.6.0才能使用。
但同時在新款的機型 F-Y20JH，這兩個版本都可以正常運行。

**Comment by osk2** [comment]
無法控制是指按了沒反應，還是實體不可用？有任何錯誤訊息嗎？

**Comment by osk2** [comment]
Closed as not receiving any response.
