### ISSUE TITLE
希望可以新增冷氣風向風力調整功能

### ISSUE THREAD

**Issue by andyching168** [osk2/panasonic_smart_app#9]
您好
你的Custom Component真的很好用，真的很感謝您!
如果有新增冷氣風向風力調整功能的話會更完善
感謝!

**Comment by osk2** [comment]
已有支援垂直風向調整，風量調整功能會再加入

**Comment by osk2** [comment]
先前回覆有誤，冷氣的垂直風向和風量調整功能都已經實作了，使用方式如下圖

![Screen Shot 2021-06-13 at 11 21 48 PM](https://user-images.githubusercontent.com/705280/121813364-4e91a900-cc9e-11eb-8801-449279abe62a.png)
