### ISSUE TITLE
請問ha更新到2024.1.10  除濕機開關實體失效

### ISSUE THREAD

**Issue by uho886** [osk2/panasonic_smart_app#92]
回報更新後,除濕機開關實體失效

**Comment by osk2** [comment]
我目前是 2024.1.2 沒有遇到問題，日誌有顯示錯誤嗎？

**Comment by uho886** [comment]
1.不好意思，是更新到2024.1.0 ,上面多打一個0
2.日誌顯示找不到日誌事件，目前就除濕機無法開關機，其他功能正常
那我先測試重新安裝，不行我在升級到2024.1.2，感謝回復

**Comment by uho886** [comment]
更新：重新安裝後，發現實體還是有問題，更新到2024.1.2就正常了，感謝
