### ISSUE TITLE
除濕機似乎無法使用了

### ISSUE THREAD

**Issue by guitarkid35** [osk2/panasonic_smart_app#93]
除濕機型號是 F-YV32LX
大約上個月開始無法使用

**Comment by osk2** [comment]
日誌有紀錄到什麼錯誤嗎？
前陣子也有人反應這個問題，後來更新 HA 就恢復了，可以試試看

**Comment by guitarkid35** [comment]
謝謝開發者，我確實更新後就可以用了，可能我太久沒有更新，我更新了一個版本就出現錯誤，原來要先更新到某個版本才能再更到最新版。

最新版就沒有問題了，謝謝。

**Comment by osk2** [comment]
根據 #92 的描述，似乎是 2024.1.0 會有問題，我目前使用 2024.1.5 都蠻正常的
