### ISSUE TITLE
冷氣的按關機圖示沒辦法關閉

### ISSUE THREAD

**Issue by mfinmuch** [osk2/panasonic_smart_app#98]
暖氣 冷氣 除濕 自動 都是正常的
但是當我要關閉冷氣 按關機圖示 (下圖紅框的部分) 會沒有反應
沒辦法將冷氣關閉
我個人有連結到 homekit 不知道是不是這個原因導致 homekit 也沒辦法關閉冷氣
![image](https://github.com/osk2/panasonic_smart_app/assets/12792709/7331711b-c418-464e-ab43-46dca40b1174)

**Comment by osk2** [comment]
日誌裡面有出現什麼錯誤嗎？

**Comment by mfinmuch** [comment]
我看 說 list index out of range 
是指這個嗎? 其他部分沒看到類似的 錯誤提示
![image](https://github.com/osk2/panasonic_smart_app/assets/12792709/00a9f896-365b-4b55-9245-8b6a21893ad7)

**Comment by mfinmuch** [comment]
![image](https://github.com/osk2/panasonic_smart_app/assets/12792709/cba99dd4-4e4f-4685-8852-787ed8bc64d0)

**Comment by osk2** [comment]
稍微看了一下可能是被洗衣機影響了，可以嘗試把洗衣機從帳號移除再調整冷氣開關
